version: '3.3'
services:
  api:
    container_name: ${APP_NAME:-local}-api
    image: ${APP_NAME:-local}-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - adminer
    networks:
      - app-network

  db:
    container_name: ${APP_NAME:-local}-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_NAME:-laravel_db}_dev
      MYSQL_USER: ${APP_NAME:-laravel_usr}-usr
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '${DB_PORT:-3306}:3306'
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
